# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
            preserve_default=False,
        ),
    ]
