# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_chat_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
